---
title: "Tidy Template"
author: "Fabio Votta"
date: "The Date"
output: html_document
---

This script is about:



## Packages and Folders

```{r}
# Install these packages if you don't have them yet
# if (!require("pacman")) install.packages("pacman")
# devtools::install_github("favstats/tidytemplate")

pacman::p_load(tidyverse, tidytemplate)

# Creates folders
# tidytemplate::data_dir()
# tidytemplate::images_dir()
```


## Load Data

```{r, data}


wk <- per_con$result$latest$parties  %>%
    # map(as.data.frame) %>% 
    set_names(1:299) %>%
    imap_dfr(~{
        raw <- as.data.frame(.x) %>% mutate(electoralId = unique(.y)) 
        
        # print(raw)
        
        if("result" %in% colnames(raw)){
            results <- raw  %>% 
                pluck("result") %>% 
                pluck("votes") 
            
            
            first_dat <- results  %>% 
                pluck("first") %>% 
                set_names(~paste0("first_", .x))
            
            
            second_dat <- results  %>% 
                pluck("second")  %>% 
                set_names(~paste0("second_", .x))
            
            raw <- bind_cols(first_dat, second_dat) %>% 
               bind_cols(select(raw, party_id = id, electoralId)) 
        }
        
        return(raw)}
        )

wk$first[[20]]
```


## Analysis / Dataviz

```{r, analysis}



```



## Conclusion